version: "3.8"

services:
  php: # docker-compose run php bash
    build: './.docker/php'
    ports:
      - "8888:80"
    tty: true
    environment:
      PHP_IDE_CONFIG: "serverName=Dating-Portal Docker"
    volumes:
      - ./:/var/www/html/
      - ./.docker/php/logs/:/var/log/apache2/
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
  composer: # docker-compose run composer bash
    build: './.docker/composer'
    tty: true
    command: [ "composer", "update" ]
    volumes:
      - ./:/app/
      - ./.docker/composer/tmp/:/tmp/
    depends_on:
      - php